### ISSUE TITLE
Classes key as a string get quotes removed on formatting

### ISSUE THREAD

**Issue by carusog** [trivago/prettier-plugin-twig-melody#44]
Given a I have a class, as a string key, that relies on a boolean variable, its wrapping quotes get removed on formatting.

That's not an issue in cases where the string uses not reserved words or characters. But, for example, with BEM modifiers classes names containing a double dash sign `--` it raises an error.

E.G.

Unformatted code:

```css
<h1 class="{{ {
        base: css.title,
        'page__headline--profile': booleanVariable
    } | classes }}">
    My title
</h1>
```

Formatted code:

```css
<h1 class="{{ {
        base: css.title,
        page__headline--profile: booleanVariable
    } | classes }}">
    My title
</h1>
```
